version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - NATS_URL=nats://nats:4222
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin@123
      - DB_NAME=golang_project
      - DB_PORT=5432
      - DB_SSLMODE=disable
      - JWT_SECRET=UlVwZFpYbGlzN2N3djd4b2lLMjV6OVF0QzM3TkFqQkY=
      - JWT_EXPIRATION_HOURS=24
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_DB=golang_project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nats:
    image: nats:2.9.15-alpine
    ports:
      - "4222:4222"
    command: "-js"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
