version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
      - "2404:2404" # IEC104 port
    environment:
      - PORT=8081
      - NATS_URL=nats://nats:4222
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=iec104
      - DB_SSLMODE=disable
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRATION_HOURS=24
      - IEC104_PORT=2404
      - IEC104_TIMEOUT=30
      - IEC104_K=12
      - IEC104_W=8
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      nats:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iec104
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    command: [ "--http_port", "8222", "--debug", "--trace" ]
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "nats-server", "-v" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
